# development:
#   adapter: postgresql
#   encoding: unicode
#   database: myapp_development
#   pool: 5
#   host: localhost
#   username: myapp
#   password: 

development:
  adapter: postgresql
  pool: 5
  # these are our new parameters
  encoding: UTF-8
  database: my_application_development
  host: localhost
  username: jamie
  password: \password

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password: